spring:
  application:
    name: serviceflow

  datasource:
    url: jdbc:mysql://localhost:3306/serviceflow
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true